/*
MOSTRAR LOS ALOJAMIENTOS DISPONIBLES EN UN RANGO DE FECHAS, QUE CUMPLEN CON UN CONJUNTO DE REQUERIMIENTOS DE DOTACIÓN O SERVICIOS.

POR EJEMPLO, COCINETA, TV CABLE, INTERNET, SALA.

*/
SELECT a.id
FROM  ALOJAMIENTOS a , SERVICIOS s
WHERE a.id= s.idalojamiento
AND s.nombre ='Jacuzzi'
AND s.tomaservicio = 'Y'
MINUS
(SELECT a.id idaloj
 FROM  ALOJAMIENTOS a , reservas r
 WHERE r.idalojamiento = a.id
 AND r.diareserva BETWEEN TO_DATE ('1/02/20') AND TO_DATE('28/03/20'));