--CREACION TABLA ALOJAMIENTOS y especificación de sus restricciones
CREATE TABLE ALOJAMIENTOS
        (ID NUMBER,
        CONSTRAINT PK_ALOJAMIENTOS PRIMARY KEY (ID));

CREATE SEQUENCE ID_ALOJAMIENTO
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1;

--CREACION TABLA OPERADORES y especificación de sus restricciones
CREATE TABLE OPERADORES
     (ID NUMBER NOT NULL,
      NOMBRE VARCHAR(255) NOT NULL,
      REGCAMARACOMERCIO CHAR(1) NOT NULL,
      SUPERTURISMO CHAR(1) NOT NULL,
      CALIDAD NUMBER NOT NULL,
      TIPOOPERADOR VARCHAR(20) NOT NULL,
      CONSTRAINT PK_OPERADORES PRIMARY KEY (ID));


ALTER TABLE OPERADORES

    ADD CONSTRAINT CK_TIPO_OPERADOR 
        CHECK (TIPOOPERADOR IN ('Hostal', 'Hotel', 'empViniendaUniv','MiembroComunidad','PersonaNatural'))
    
    ADD CONSTRAINT CK_REG_CAMARA_COMERCIO
        CHECK (REGCAMARACOMERCIO IN ('Y', 'N'))
    
    ADD CONSTRAINT CK_SUPER_TURISMO
        CHECK (SUPERTURISMO IN ('Y', 'N'))

    ADD CONSTRAINT CK_CALIDAD
        CHECK (CALIDAD >=0 AND CALIDAD<=5)

ENABLE;


--CREACION TABLA SERVICIOS  y especificación de sus restricciones
CREATE TABLE SERVICIOS
    (ID NUMBER ,
        IDALOJAMIENTO NUMBER NOT NULL,
          DESCRIPCION VARCHAR(255) NOT NULL,
          NOMBRE VARCHAR(255) NOT NULL,
          PRECIO NUMBER NOT NULL, 
          TOMASERVICIO CHAR(1) NOT NULL, 
          CONSTRAINT PK_SERVICIOS PRIMARY KEY (ID)
    );
        
ALTER TABLE SERVICIOS
                  
    ADD CONSTRAINT CK_TOMA_SERVICO
        CHECK (TOMASERVICIO IN ('Y','N'))

    ADD CONSTRAINT FK_SERVICIOS_ALOJAMIENTO
        FOREIGN KEY(IDALOJAMIENTO)
        REFERENCES ALOJAMIENTOS(ID)
        --CAMBIARAR  PIEORENMKCNO[VRDLVN R]RDN VRO]ARARARRAA
ENABLE;

--CREACION TABLA VIVIENDA COMUNIDAD y especificación de sus restricciones
CREATE TABLE VIVIENDACOMUNIDAD
        ( IDALOJAMIENTO NUMBER ,
          IDOPERADOR NUMBER NOT NULL, 
          DIRECCION VARCHAR(255) NOT NULL, 
          PRECIO NUMBER NOT NULL, 
          NUMHABITACIONES NUMBER NOT NULL, 
          MENAJE CHAR(1) NOT NULL,
          SEGUROARRIENDO CHAR(1) NOT NULL,
          CARACTSEGURO VARCHAR(255) NOT NULL,
          CONSTRAINT PK_VIVIENDACOMUNIDAD PRIMARY KEY (IDALOJAMIENTO)
        );

ALTER TABLE VIVIENDACOMUNIDAD

    ADD CONSTRAINT CK_SEGUROARRIENDO
        CHECK (SEGUROARRIENDO IN ('Y', 'N'))
    
    ADD CONSTRAINT CK_MENAJE
        CHECK (MENAJE IN ('Y', 'N'))

    ADD CONSTRAINT CK_PRECIO
        CHECK (PRECIO >=0)   
        
    ADD CONSTRAINT FK_V_ALOJAMIENTO
        FOREIGN KEY(IDALOJAMIENTO)
        REFERENCES ALOJAMIENTOS(ID)
        ON DELETE CASCADE

    ADD CONSTRAINT FK_V_OPERADORES
        FOREIGN KEY(IDOPERADOR)
        REFERENCES OPERADORES(ID)
    
ENABLE;

--CREACION TABLA HABITACIONES y especificación de sus restricciones
CREATE TABLE HABITACIONES
          ( IDALOJAMIENTO NUMBER ,
            IDOPERADOR NUMBER NOT NULL,
            DIRECCION VARCHAR(255) NOT NULL, 
            PRECIO NUMBER NOT NULL, 
            NUMHABITACION VARCHAR(255) NOT NULL, 
            TIPOHABITACION VARCHAR(11) NOT NULL, 
            TIPOOPHAB VARCHAR(15) NOT NULL,
            CONSTRAINT PK_HABITACIONES PRIMARY KEY (IDALOJAMIENTO)
          );
        
ALTER TABLE HABITACIONES

    ADD CONSTRAINT CK_TIPO_HABITACION
        CHECK (TIPOHABITACION IN ('Estandar', 'Semisuite', 'Suite','Individual','Compartida'))

    ADD CONSTRAINT CK_TIPO_OP_HAB 
        CHECK (TIPOOPHAB IN ('Hostal', 'Hotel', 'ViviendaUniv','PersonaNatural'))
        
    ADD CONSTRAINT FK_H_ALOJAMIENTO
        FOREIGN KEY(IDALOJAMIENTO)
        REFERENCES ALOJAMIENTOS(ID)
        ON DELETE CASCADE
        
    ADD CONSTRAINT FK_H_OPERADORES
        FOREIGN KEY(IDOPERADOR)
        REFERENCES OPERADORES(ID)
   
    
ENABLE;

--CREACION TABLA MIEMBROS COMUNIDAD UNIVERCITARIA y especificación de sus restricciones--
CREATE TABLE MIEM_CO_UNIV
            ( ID NUMBER,
              TIPOID VARCHAR(255) NOT NULL,
              NOMBRE VARCHAR(255) NOT NULL,
              TIPOMIEMBRO VARCHAR(255) NOT NULL,
              CONSTRAINT PK_MCU PRIMARY KEY (ID, TIPOID)
            );

ALTER TABLE MIEM_CO_UNIV
    
    ADD CONSTRAINT CK_TIPO_MIEMBRO
        CHECK (TIPOMIEMBRO IN ('Estudiante', 'Egresado', 'Empleado', 'Profesor', 'PadreInvitado', 'ProfesorInvitado', 'PersonaEvento'))

ENABLE;


--CREACION RESERVAS y especificación de sus restricciones--
CREATE TABLE RESERVAS
            ( NUMRESERVA NUMBER,
              IDALOJAMIENTO NUMBER NOT NULL,
              IDMIEMBRO NUMBER NOT NULL,
              TIPOID VARCHAR(255) NOT NULL,
              DIARESERVA DATE NOT NULL,
              TIEMPODIAS NUMBER NOT NULL,
              CONSTRAINT PK_RESERVAS PRIMARY KEY (NUMRESERVA)
            );
            
ALTER TABLE RESERVAS

    ADD CONSTRAINT FK_R_ALOJAMIENTO
        FOREIGN KEY(IDALOJAMIENTO)
        REFERENCES ALOJAMIENTOS(ID)
        
    ADD CONSTRAINT FK_R_ID_TIPO
        FOREIGN KEY(IDMIEMBRO, TIPOID)
        REFERENCES MIEM_CO_UNIV(ID, TIPOID)  
        
ENABLE;

CREATE SEQUENCE ID_RESERVA
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1;

--CREACION APARTAMENTOS y especificación de sus restricciones--
CREATE TABLE APARTAMENTOS
            ( IDALOJAMIENTO NUMBER,
              DIRECCION VARCHAR(255) NOT NULL,
              PRECIO NUMBER NOT NULL,
              DUEÑO NUMBER NOT NULL,
              VALORADMIN NUMBER NOT NULL,
              AMOBLADO CHAR(1) NOT NULL,
              CONSTRAINT PK_APARTAMENTOS PRIMARY KEY (IDALOJAMIENTO)
            );
            
ALTER TABLE APARTAMENTOS 

    ADD CONSTRAINT FK_A_ALOJAMIENTOS
        FOREIGN KEY(IDALOJAMIENTO)
        REFERENCES ALOJAMIENTOS(ID)
        ON DELETE CASCADE
    
    ADD CONSTRAINT CK_PRECIO_A
        CHECK (PRECIO > 0)
        
    ADD CONSTRAINT FK_A_OPERADOR
        FOREIGN KEY (DUEÑO)
        REFERENCES OPERADORES(ID)
        
    ADD CONSTRAINT CK_AMOBLADO
        CHECK (AMOBLADO IN('Y', 'N'))
        
ENABLE;

COMMIT;

DROP TABLE "ALOJAMIENTOS" CASCADE CONSTRAINTS;
DROP SEQUENCE ID_ALOJAMIENTO;
DROP SEQUENCE ID_RESERVA;
DROP TABLE "OPERADORES" CASCADE CONSTRAINTS;
DROP TABLE "SERVICIOS" CASCADE CONSTRAINTS;
DROP TABLE "VIVIENDACOMUNIDAD" CASCADE CONSTRAINTS;
DROP TABLE "HABITACIONES" CASCADE CONSTRAINTS;
DROP TABLE "MIEM_CO_UNIV" CASCADE CONSTRAINTS;
DROP TABLE "RESERVAS" CASCADE CONSTRAINTS;
DROP TABLE "APARTAMENTOS" CASCADE CONSTRAINTS;