--- Sentencias SQL para la creaci�n del esquema de parranderos
--- Las tablas tienen prefijo A_ para facilitar su acceso desde SQL Developer

DROP TABLE "ALOJAMIENTOS" CASCADE CONSTRAINTS;
DROP SEQUENCE ID_ALOJAMIENTO;
DROP SEQUENCE ID_RESERVA;
DROP SEQUENCE ID_SERVICIOS;
DROP TABLE "OPERADORES" CASCADE CONSTRAINTS; 
DROP TABLE "SERVICIOS" CASCADE CONSTRAINTS;
DROP TABLE "VIVIENDACOMUNIDAD" CASCADE CONSTRAINTS; 
DROP TABLE "HABITACIONES" CASCADE CONSTRAINTS; 
DROP TABLE "MIEM_CO_UNIV" CASCADE CONSTRAINTS; 
DROP TABLE "RESERVAS" CASCADE CONSTRAINTS;
DROP TABLE "APARTAMENTOS" CASCADE CONSTRAINTS;

commit;


